### ISSUE TITLE
no rule to make target

### ISSUE THREAD

**Issue by manuprendlair** [darklord4822/android_kernel_homtom_ht17#1]
Hello Darklord,

I try to compile your kernel as is with the last NDK 64bits toolchain and aarch64 (but same problem in arm)
and I have this error:
make[2]: *** No rule to make target `net/xfrm/xfrm_policy.o', needed by `net/xfrm/built-in.o'.  Stop.

Could you please help me?
(my project is to make a kernel with the uvc support)

Best Regards.

Emmanuel

**Comment by darklord4822** [comment]
Hello, Emmanuel.
You are missing file xfrm_policy.c

**Comment by manuprendlair** [comment]
Thanks for your answer Vitaly.
I compile the kernel as is, after make homtom_ht17_32_defconfig or homtom_ht17_64_defconfig.
So why is it missing? Why you haven't same error when you compile the kernel? (could you tell me what you use to compile?)
 I search google but didn't find information.

Thanks to help

**Comment by manuprendlair** [comment]
Ok, you're right Vitaly!
I check my source code I got as a zip file from your repository...and the xfrm_policy.c is missing!
So I git clone the souce code and all is here and I am able to compile!! That's crazzy!

So issue is closed

**Comment by darklord4822** [comment]
Okay :)
